---
- name: SSH Key Exchange Task
  hosts: source_group
  become: false  # Run as ansible_user (backupuser)
  vars:
    ansible_user: "backupuser"

  tasks:
    - name: Generate SSH key on source host (if not exists)
      become: yes
      become_user: "{{ ansible_user }}"
      command: ssh-keygen -t rsa -b 4096 -f /home/{{ ansible_user }}/.ssh/id_rsa -q -N ""
      args:
        creates: /home/{{ ansible_user }}/.ssh/id_rsa

    - name: Read SSH public key from source host
      slurp:
        src: /home/{{ ansible_user }}/.ssh/id_rsa.pub
      register: ssh_key_raw

    - name: Store SSH public key as fact
      become: yes
      become_user: "{{ ansible_user }}"
      set_fact:
        ssh_public_key: "{{ ssh_key_raw.content | b64decode }}"

- name: Copy SSH Key to Destination
  hosts: destination_group
  become: false  # Run as ansible_user (backupuser)
  vars:
    ansible_user: "backupuser"

  tasks:
    - name: Add SSH key to authorized_keys on destination
      authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ hostvars[groups['source_group'][0]]['ssh_public_key'] }}"


